### ISSUE TITLE
时间或密码不合法

### ISSUE THREAD

**Issue by 15930158351** [ZTO-Express/zopsdk-java#1]
我把项目完全down下来，运行main方法，返回值为
{"result":false,"data":null,"message":"时间或密码不合法"}
请问我该怎么做

**Comment by chocotan** [comment]
datetime或verify字段错误
datetime请使用当前时间，verify字段请按照中通文档说明传值（测试环境使用ZTO123，生产环境请联系网点）
----------------------
天羽ちよこ <loli@linux.com>
Github: https://github.com/chocotan



15930158351 <notifications@github.com> 于2019年8月14日周三 下午6:25写道：
