### ISSUE TITLE
有关云打印接口的问题

### ISSUE THREAD

**Issue by lexingrensheng** [ZTO-Express/zopsdk-java#3]
我们公司每个月需要快递大量发票信息和明细信息，这块打印可以放在你们那边打印并邮寄么

**Comment by chocotan** [comment]
业务方面的问题请加群咨询

点击链接加入群聊【中通开放平台交流2群】：https://jq.qq.com/?_wv=1027&k=53uB9CM


lexing <notifications@github.com> 于2019年8月15日周四 下午5:25写道：
